### ISSUE TITLE
Syntax highlight issue

### ISSUE THREAD

**Issue by jimpriest** [andriyko/sublime-robot-framework-assistant#222]
This is properly colored with a purple keyword:

User click on a finding with Pending Program status
    ${count}=    Get Element Count  ${findings_table_rows}

If I change 'user' to 'I' it turns white:

I click on a finding with Pending Program status
    ${count}=    Get Element Count  ${findings_table_rows}

**Comment by aaltat** [comment]
I understand your problem. Unfortunately I don't have time to investigate and fix it, because SeleniumLibrary development is taking all my available time for open source. Most likely bug is in here: https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/Robot.tmLanguage

I am actively looking for a new lead developer for the project, would you happen to know anyone who would be interested?

**Comment by jsdavis** [comment]
#223 That I just submitted might have inadvertently fixed this? In my sample file I used a few test cases that started with "I" and they worked

**Comment by andriyko** [comment]
@jimpriest , does the fix #223 resolve your issue?

**Comment by jimpriest** [comment]
Yes!  I had actually hacked up a similar fix of my own but @jsdavis  beat me to it.
