### ISSUE TITLE
Keywords from Selenium2Library are not displayed in autocompletion and no documentation about them is shown

### ISSUE THREAD

**Issue by georgecarstoiu** [andriyko/sublime-robot-framework-assistant#99]
Despite the fact that there is a json in the Index folder for Selenium2Library, its keywords are not shown in auto-completion or in the documentation.

**Comment by georgecarstoiu** [comment]
Same with SSHlibrary

**Comment by aaltat** [comment]
I can't reproduce the problem with these details. Could you tell which version of Sublime you are using and which version of the plugin you have installed?

If you are using the 3.X.X series, could you describe your test data with simple example. The most relevant information is where the libraries have been imported and where the auto completion didn't work. And is there import path between those two files. It would be even better if you could send a example which I could use to debug the problem.

**Comment by georgecarstoiu** [comment]
Using Sublime Text 3 x64 - build 3103 with Robot Framework Assistant 3.1.0 (the one that installs from Package Control)

Have been trying to recreate a small scenario but I have been running to another issue when generating the db. The log is giving me this and SBT3 is stuck (it happened to me a few times today - usually I had to reinstall the plugin and then it worked just fine, but apparently not even that works):

INFO:2016-04-27 18:32:24,565: Creating table for: c:\sbt3\testcase.robot
INFO:2016-04-27 18:32:24,565: Creating table for: Selenium2Library
INFO:2016-04-27 18:32:24,674: Capture Page Screenshot will be run on failure.
INFO:2016-04-27 18:32:24,714: Creating table for: c:\sbt3\keywords.robot
INFO:2016-04-27 18:32:24,714: Creating table for: BuiltIn
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\__init__.py", line 84, in <module>
    import _multiprocessing
ImportError: DLL load failed: %1 is not a valid Win32 application.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\__init__.py", line 84, in <module>
    import _multiprocessing

Regarding the set-up it is like this:
**1 file has the testcases -> Testcases.robot**

*** Settings ***
Library           Selenium2Library
Resource          keywords.robot

*** Testcases ***
Test IMDB
	Open Browser To IMDB
	Search text
	Close browser

**1 file has the keywords -> keywords.robot**

*** Keywords ***
Open Browser To IMDB
    Open Browser    https://www.imdb.com      firefox
    Maximize Browser Window

Search text
    Input text      id=navbar-query     test
    Click button    //*[@id="navbar-submit-button"]

**The default settings look like this:**

{
 
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": true,
    "draw_white_space": "all",
    "word_separators": "./\\()\"'-:,.;<>~!@#$%^&|+=[]{}`~?",    
    "robot_framework_workspace": "C:\\sbt3",
    "robot_framework_keyword_argument_format": false,  
    "robot_framework_extension": "robot",  
    "path_to_python": "C:\\Python27\\python.exe",  
    "robot_framework_module_search_path":
        [
            "/path/to/libs",
            "/other/path/to/libraries"
        ], 
    "robot_framework_libraries_in_xml": "/path/to/library/documentation", 
    "robot_framework_builtin_variables":
        [
            "${/}",
            "${:}",
            "${\\n}",
            "${CURDIR}",
            "${DEBUG_FILE}",
            "${EMPTY}",
            "@{EMPTY}",
            "&{EMPTY}",
            "${EXECDIR}",
            "${False}",
            "${LOG_FILE}",
            "${LOG_LEVEL}",
            "${None}",
            "${null}",
            "${OUTPUT_DIR}",
            "${OUTPUT_FILE}",
            "${PREV_TEST_MESSAGE}",
            "${PREV_TEST_NAME}",
            "${PREV_TEST_STATUS}",
            "${REPORT_FILE}",
            "${SPACE}",
            "${SUITE_DOCUMENTATION}",
            "${SUITE_NAME}",
            "${SUITE_SOURCE}",
            "${TEMPDIR}",
            "${TEST_DOCUMENTATION}",
            "${TEST_NAME}",
            "${True}",
            "&{SUITE_METADATA}",
            "@{TEST_TAGS}"
        ]
}


When it did work, a json was created in the 'index' folder for selenium2library, but I couldn't see any autocomplete or documentation in the keywords file (builtin and string for example were working just fine).

Hope this helps in any way as I really love the work you've done with this plugin.

**Comment by aaltat** [comment]
1) The plugin hang also happens to me, but very rarely. When it happens, I see same error message in the `scan_index.log` file. For me the plugin hangs only right after I have started the Sublime. I have done some investigation on the matter, but have not found a reason for it or a way to reproduce the problem in a reliable manner. I did raise a new issue #100 about it, so that I will remember to resume the issue investigation in the near future. If you find a way to reproduce the problem every time or could provide some additional information please write updates to the #100 issue. 

As a workaround, at least for me, I first run the `Robot Framework: Create Database Tables` command and then rest of the commands work without errors. Also if the problem happens, I too need to reinstall the plugin to resolve the issue.

2) When you run the `Robot Framework: Create Database`, successfully, it is expected the Selenium2Library are available in the `Testcases.robot` file and the Selenium2Library keyword completion should work in the `Testcases.robot` file. If it does not work, then it is a bug in the plugin which needs to be found and fixed.

But from the `keywords.robot` file point of view, the Selenium2Library is not available nad therefore the Selenium2Library keyword completion does not work. Perhaps an example explains the situation better. If you think the test case and resource files in tree form, like in the picture in below. 
![binary_tree](https://cloud.githubusercontent.com/assets/2665023/14866296/98ca3d04-0ccb-11e6-847f-91c25b64d25b.png)
Where the A is the test suite file and rest of the nodes are resource files. A imports the B and C in the settings table, B imports D and C imports E and F. In Robot there is relation from up to down direction in the tree, example by looking from A it knows which keywords and variables are available from it's siblings (from from it self). But there is not relation from down to up direction. In Robot, the E does not know, where it has been used, when looking the inheritance path of Robot data. Therefore the plugin does not know, that `keywords.robot` has Selenium2Library keyword available when it is being used from the `Testcases.robot` file. And if there would be other test suite file, which does not import Selenium2Library then the keyword completion should not work in the `keywords.robot`. Because of this problems in the imports, the plugin does not provide Selenium2Library inthe `keywords.robot` file.

If this was your problem, you could import the Selenium2Library in the `keywords.robot` file. Then `keywords.robot` and `Testcases.robot` file should provide the keyword completion from the Selenium2Library.

**Comment by georgecarstoiu** [comment]
For the first problem I will keep an open eye to see if I can find some clear steps to reproduce the problem.

For the second problem I actually thought about what you described with the graph which makes perfect sense, but then I couldn't understand why some other libraries were available like the String and Builtin. And yes, of course Builtin is available because it is a global one, but the String one shouldn't be right? If the solution is as easy as just importing the libraries in the keywords document, then it should be fast. Will have to try it and see.

Thanks for the support!

**Comment by aaltat** [comment]
The BuiltIn library is always available because it also always available in the Robot data. The String library should be only available when it is explicitly imported. If that is not the case, then it is a bug in the plugin which should be fixed. Can you describe the problem with String library and provide some details to so that I can reproduce it too?

**Comment by georgecarstoiu** [comment]
Moved all the imports in the keywords file and everything is being displayed.

Just realized that with String library I was mistaking some keywords from BuiltIn as being from String. My bad! :P

So all good with the imports of keywords!

**Comment by aaltat** [comment]
It seems that problem is fixed, can we close the issue?

**Comment by georgecarstoiu** [comment]
From my point of view, yes.
